USE onlinestore;
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (1, 'David', 'None', 'Product', 'Desinfectant', 'Pires', 887.83, 6540);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (2, 'Bianca', 'None', 'Product', 'Air Care', 'Guerreiro', 638.97, 7583);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (3, 'Diego', 'None', 'Product', 'Air Care', 'Pinheiro', 150.32, 9620);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (4, 'Sara', 'None', 'Service', 'Fabric Softener', 'Amorim', 438.35, 2587);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (5, 'Rui', 'None', 'Service', 'Desinfectant', 'Ribeiro', 797.69, 6738);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (6, 'Guilherme', 'None', 'Service', 'Air Care', 'Carneiro', 620.48, 562);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (7, 'Núria', 'None', 'Product', 'Air Care', 'Garcia', 513.1, 1540);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (8, 'Benjamim', 'None', 'Product', 'Moisturizing', 'Batista', 127.23, 6280);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (9, 'Lisandro', 'None', 'Product', 'Detergent', 'Vieira', 3.6, 9324);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (10, 'William', 'None', 'Product', 'Detergent', 'Lima', 961.99, 9169);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (11, 'Vasco', 'None', 'Service', 'Air Care', 'Paiva', 268.48, 3750);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (12, 'Clara', 'None', 'Product', 'Detergent', 'Machado', 113.1, 2499);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (13, 'Yara', 'None', 'Service', 'House Cleaners', 'Moreira', 729.76, 2988);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (14, 'Ismael', 'None', 'Product', 'Moisturizing', 'Mota', 541.61, 3979);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (15, 'Mia', 'None', 'Service', 'Fabric Softener', 'Melo', 581.55, 556);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (16, 'Yasmin', 'None', 'Product', 'Detergent', 'Valente', 44.68, 8966);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (17, 'Alícia', 'None', 'Product', 'Detergent', 'Neves', 195.42, 7440);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (18, 'Ângelo', 'None', 'Product', 'Detergent', 'Gaspar', 840.84, 5504);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (19, 'Letícia', 'None', 'Service', 'Moisturizing', 'Costa', 752.54, 7870);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (20, 'Nuno', 'None', 'Service', 'Fabric Softener', 'Machado', 326.6, 2978);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (21, 'Xavier', 'None', 'Service', 'House Cleaners', 'Vicente', 332.88, 2803);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (22, 'Miriam', 'None', 'Service', 'Fabric Softener', 'Coelho', 570.7, 3634);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (23, 'Sofia', 'None', 'Product', 'House Cleaners', 'Pires', 436.82, 6682);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (24, 'Juliana', 'None', 'Service', 'House Cleaners', 'Batista', 517.0, 4659);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (25, 'Nair', 'None', 'Product', 'Moisturizing', 'Silva', 323.78, 2741);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (26, 'Renata', 'None', 'Service', 'Detergent', 'Pinheiro', 148.37, 7194);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (27, 'Melissa', 'None', 'Service', 'Air Care', 'Monteiro', 828.5, 7822);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (28, 'Sofia', 'None', 'Product', 'Fabric Softener', 'Gonçalves', 964.68, 7409);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (29, 'Cristiano', 'None', 'Service', 'House Cleaners', 'Silva', 386.24, 2440);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (30, 'Wilson', 'None', 'Service', 'House Cleaners', 'Azevedo', 611.57, 6836);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (31, 'Brian', 'None', 'Service', 'Desinfectant', 'Santos', 867.84, 8997);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (32, 'William', 'None', 'Service', 'Moisturizing', 'Guerreiro', 433.74, 4306);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (33, 'Íris', 'None', 'Service', 'Fabric Softener', 'Silva', 346.76, 85);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (34, 'Ana', 'None', 'Service', 'Air Care', 'Loureiro', 360.96, 7247);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (35, 'Kévim', 'None', 'Product', 'Desinfectant', 'Figueiredo', 214.97, 393);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (36, 'Maria', 'None', 'Service', 'Air Care', 'Vieira', 599.0, 9079);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (37, 'Joel', 'None', 'Product', 'Air Care', 'Costa', 744.4, 2911);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (38, 'Hugo', 'None', 'Product', 'Fabric Softener', 'Azevedo', 358.91, 5562);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (39, 'Lorena', 'None', 'Service', 'Desinfectant', 'Machado', 835.85, 4220);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (40, 'Mara', 'None', 'Service', 'Air Care', 'Assunção', 744.0, 9127);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (41, 'Francisco', 'None', 'Service', 'Air Care', 'Nogueira', 847.4, 7984);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (42, 'Leonor', 'None', 'Service', 'Desinfectant', 'Neves', 186.41, 4154);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (43, 'Gustavo', 'None', 'Product', 'Detergent', 'Gaspar', 62.85, 7900);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (44, 'Patrícia', 'None', 'Product', 'Air Care', 'Araújo', 701.77, 8118);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (45, 'Guilherme', 'None', 'Product', 'Detergent', 'Soares', 343.51, 5739);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (46, 'Guilherme', 'None', 'Product', 'Moisturizing', 'Mendes', 753.28, 1370);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (47, 'Emília', 'None', 'Product', 'Air Care', 'Correia', 500.43, 1965);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (48, 'Emília', 'None', 'Service', 'Desinfectant', 'Matias', 329.4, 8787);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (49, 'Matias', 'None', 'Product', 'Fabric Softener', 'Azevedo', 456.2, 3382);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (50, 'Luís', 'None', 'Product', 'Air Care', 'Tavares', 237.32, 1394);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (51, 'Diego', 'None', 'Product', 'House Cleaners', 'Rodrigues', 197.71, 1235);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (52, 'Rui', 'None', 'Service', 'Desinfectant', 'Silva', 708.65, 9107);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (53, 'Sofia', 'None', 'Product', 'Desinfectant', 'Matias', 153.86, 1552);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (54, 'Lia', 'None', 'Service', 'Fabric Softener', 'Borges', 316.65, 189);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (55, 'Henrique', 'None', 'Service', 'Desinfectant', 'Sousa', 23.59, 3987);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (56, 'Afonso', 'None', 'Product', 'Desinfectant', 'Branco', 587.79, 9427);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (57, 'Emília', 'None', 'Product', 'Moisturizing', 'Paiva', 290.97, 8130);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (58, 'Violeta', 'None', 'Service', 'House Cleaners', 'Baptista', 923.12, 2015);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (59, 'Diana', 'None', 'Product', 'Detergent', 'Matos', 5.96, 3653);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (60, 'Alexandra', 'None', 'Product', 'Desinfectant', 'Sá', 532.48, 6740);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (61, 'Renato', 'None', 'Service', 'Air Care', 'Ferreira', 35.99, 61);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (62, 'Clara', 'None', 'Service', 'House Cleaners', 'Andrade', 182.55, 6665);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (63, 'António', 'None', 'Service', 'House Cleaners', 'Paiva', 576.23, 5791);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (64, 'Jorge', 'None', 'Product', 'Fabric Softener', 'Alves', 608.7, 1911);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (65, 'William', 'None', 'Product', 'House Cleaners', 'Barros', 121.18, 2755);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (66, 'Sandro', 'None', 'Service', 'Desinfectant', 'Ramos', 589.56, 3693);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (67, 'Ema', 'None', 'Product', 'Desinfectant', 'Paiva', 231.28, 633);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (68, 'Filipa', 'None', 'Product', 'Air Care', 'Pacheco', 617.77, 1844);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (69, 'Márcio', 'None', 'Service', 'Moisturizing', 'Valente', 350.4, 9894);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (70, 'Valentim', 'None', 'Product', 'House Cleaners', 'Sá', 318.75, 4380);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (71, 'Flor', 'None', 'Service', 'Detergent', 'Miranda', 379.68, 4496);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (72, 'Diana', 'None', 'Service', 'Desinfectant', 'Costa', 837.85, 8511);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (73, 'Lia', 'None', 'Service', 'Fabric Softener', 'Freitas', 664.35, 9112);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (74, 'Benjamim', 'None', 'Product', 'Fabric Softener', 'Neto', 338.43, 3957);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (75, 'César', 'None', 'Product', 'Detergent', 'Abreu', 437.45, 1058);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (76, 'Paulo', 'None', 'Service', 'Fabric Softener', 'Faria', 447.25, 2172);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (77, 'Soraia', 'None', 'Product', 'Moisturizing', 'Ramos', 720.78, 1583);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (78, 'Raquel', 'None', 'Product', 'Air Care', 'Maia', 93.5, 1086);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (79, 'Bárbara', 'None', 'Product', 'Air Care', 'Jesus', 26.4, 9597);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (80, 'Ivo', 'None', 'Service', 'House Cleaners', 'Campos', 325.11, 1866);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (81, 'Alícia', 'None', 'Service', 'House Cleaners', 'Valente', 677.59, 9798);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (82, 'Nicole', 'None', 'Service', 'Fabric Softener', 'Borges', 993.69, 330);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (83, 'Sérgio', 'None', 'Product', 'Moisturizing', 'Gomes', 92.52, 8456);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (84, 'Iara', 'None', 'Service', 'House Cleaners', 'Guerreiro', 868.34, 9294);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (85, 'Frederico', 'None', 'Product', 'House Cleaners', 'Marques', 217.89, 3184);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (86, 'Yasmin', 'None', 'Product', 'Air Care', 'Pacheco', 356.79, 5629);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (87, 'Enzo', 'None', 'Product', 'Air Care', 'Vieira', 193.73, 2521);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (88, 'Fábio', 'None', 'Service', 'Moisturizing', 'Nogueira', 162.38, 8156);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (89, 'Carminho', 'None', 'Service', 'Desinfectant', 'Pires', 610.15, 9860);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (90, 'Eduarda', 'None', 'Service', 'Desinfectant', 'Torres', 945.98, 9216);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (91, 'Bárbara', 'None', 'Service', 'Air Care', 'Vieira', 952.47, 7558);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (92, 'Leandro', 'None', 'Service', 'Moisturizing', 'Henriques', 4.48, 8939);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (93, 'Ivo', 'None', 'Service', 'Desinfectant', 'Moreira', 817.97, 6810);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (94, 'Bruna', 'None', 'Product', 'Moisturizing', 'Cruz', 192.85, 3161);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (95, 'Tomé', 'None', 'Service', 'Air Care', 'Costa', 840.33, 8684);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (96, 'Wilson', 'None', 'Product', 'Detergent', 'Monteiro', 583.91, 2981);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (97, 'Rodrigo', 'None', 'Service', 'Detergent', 'Oliveira', 590.8, 8679);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (98, 'Madalena', 'None', 'Service', 'Air Care', 'Almeida', 944.76, 4104);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (99, 'Duarte', 'None', 'Product', 'House Cleaners', 'Rodrigues', 539.89, 7354);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (100, 'Lorena', 'None', 'Product', 'Moisturizing', 'Gomes', 242.3, 6638);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (101, 'Tomé', 'None', 'Product', 'Air Care', 'Pires', 731.54, 7556);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (102, 'Luís', 'None', 'Service', 'Fabric Softener', 'Pires', 535.25, 4403);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (103, 'Petra', 'None', 'Service', 'Moisturizing', 'Miranda', 736.34, 6974);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (104, 'Lúcia', 'None', 'Service', 'House Cleaners', 'Anjos', 709.34, 8236);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (105, 'Íris', 'None', 'Product', 'Desinfectant', 'Lopes', 66.35, 412);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (106, 'Andreia', 'None', 'Service', 'Fabric Softener', 'Pires', 301.65, 8258);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (107, 'Igor', 'None', 'Service', 'Desinfectant', 'Simões', 551.36, 7736);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (108, 'Kelly', 'None', 'Service', 'Air Care', 'Matias', 523.68, 489);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (109, 'Emanuel', 'None', 'Service', 'Air Care', 'Neto', 566.53, 2546);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (110, 'Guilherme', 'None', 'Product', 'Fabric Softener', 'Carvalho', 647.16, 62);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (111, 'Isabel', 'None', 'Service', 'Air Care', 'Araújo', 148.0, 8926);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (112, 'Cláudio', 'None', 'Product', 'Fabric Softener', 'Almeida', 119.99, 6384);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (113, 'Igor', 'None', 'Product', 'Detergent', 'Loureiro', 712.55, 3337);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (114, 'Emanuel', 'None', 'Service', 'Air Care', 'Teixeira', 443.4, 6608);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (115, 'Renata', 'None', 'Product', 'Fabric Softener', 'Rodrigues', 406.61, 7825);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (116, 'Victória', 'None', 'Service', 'Air Care', 'Martins', 889.83, 1351);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (117, 'Amélia', 'None', 'Product', 'Desinfectant', 'Gomes', 555.75, 1288);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (118, 'Kévim', 'None', 'Product', 'Air Care', 'Loureiro', 515.13, 7523);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (119, 'Naiara', 'None', 'Product', 'Fabric Softener', 'Lopes', 17.23, 5085);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (120, 'Márcio', 'None', 'Product', 'Detergent', 'Valente', 659.28, 1422);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (121, 'Larissa', 'None', 'Service', 'Desinfectant', 'Baptista', 729.48, 927);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (122, 'Wilson', 'None', 'Service', 'Desinfectant', 'Henriques', 831.36, 5485);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (123, 'Iara', 'None', 'Product', 'Detergent', 'Barbosa', 549.95, 5233);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (124, 'César', 'None', 'Service', 'Detergent', 'Ribeiro', 695.78, 7251);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (125, 'Fabiana', 'None', 'Service', 'Air Care', 'Maia', 553.4, 6684);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (126, 'Rafael', 'None', 'Service', 'Desinfectant', 'Melo', 849.16, 9682);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (127, 'Tomé', 'None', 'Product', 'Fabric Softener', 'Nascimento', 902.9, 2721);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (128, 'Victória', 'None', 'Service', 'Moisturizing', 'Amorim', 157.17, 193);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (129, 'Mauro', 'None', 'Product', 'House Cleaners', 'Henriques', 854.63, 4612);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (130, 'Yasmin', 'None', 'Service', 'House Cleaners', 'Loureiro', 780.65, 6620);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (131, 'Lúcia', 'None', 'Product', 'Desinfectant', 'Brito', 961.99, 7564);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (132, 'Miguel', 'None', 'Product', 'Moisturizing', 'Cardoso', 244.34, 1480);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (133, 'Marco', 'None', 'Service', 'Air Care', 'Ribeiro', 41.43, 5493);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (134, 'Filipe', 'None', 'Product', 'Detergent', 'Carvalho', 575.19, 8915);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (135, 'Lourenço', 'None', 'Product', 'Fabric Softener', 'Loureiro', 872.52, 6691);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (136, 'Mafalda', 'None', 'Product', 'Detergent', 'Pinto', 781.6, 8543);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (137, 'Márcio', 'None', 'Service', 'Moisturizing', 'Figueiredo', 325.35, 3671);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (138, 'Inês', 'None', 'Service', 'Moisturizing', 'Brito', 595.66, 5306);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (139, 'Hugo', 'None', 'Service', 'Moisturizing', 'Machado', 440.8, 9582);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (140, 'Noah', 'None', 'Service', 'Moisturizing', 'Antunes', 673.37, 8858);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (141, 'Micael', 'None', 'Service', 'Desinfectant', 'Pinho', 505.86, 8420);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (142, 'Rodrigo', 'None', 'Product', 'Air Care', 'Maia', 772.8, 4448);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (143, 'Eduardo', 'None', 'Product', 'Moisturizing', 'Neves', 9.86, 794);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (144, 'Beatriz', 'None', 'Service', 'Fabric Softener', 'Pinto', 481.51, 2376);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (145, 'Isaac', 'None', 'Product', 'House Cleaners', 'Leite', 282.92, 4805);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (146, 'Alice', 'None', 'Service', 'Fabric Softener', 'Teixeira', 838.44, 9611);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (147, 'Maria', 'None', 'Product', 'Fabric Softener', 'Carneiro', 973.32, 9348);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (148, 'André', 'None', 'Service', 'Detergent', 'Maia', 297.9, 4060);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (149, 'Bianca', 'None', 'Service', 'Fabric Softener', 'Pinho', 643.31, 7907);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (150, 'Afonso', 'None', 'Product', 'Fabric Softener', 'Domingues', 763.65, 3347);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (151, 'Ismael', 'None', 'Service', 'Detergent', 'Teixeira', 850.79, 5245);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (152, 'Nelson', 'None', 'Product', 'Moisturizing', 'Gaspar', 240.63, 5953);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (153, 'Joel', 'None', 'Service', 'Desinfectant', 'Valente', 483.15, 886);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (154, 'Luísa', 'None', 'Product', 'Moisturizing', 'Lourenço', 415.82, 7913);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (155, 'Raquel', 'None', 'Service', 'Air Care', 'Sousa', 211.79, 8916);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (156, 'Lorena', 'None', 'Product', 'Fabric Softener', 'Teixeira', 855.43, 1442);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (157, 'Kyara', 'None', 'Product', 'Air Care', 'Brito', 351.74, 7273);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (158, 'Ângelo', 'None', 'Service', 'Detergent', 'Pereira', 789.8, 423);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (159, 'Bianca', 'None', 'Service', 'Fabric Softener', 'Cunha', 381.9, 9733);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (160, 'Salvador', 'None', 'Service', 'Moisturizing', 'Teixeira', 302.81, 6241);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (161, 'Mário', 'None', 'Product', 'Desinfectant', 'Castro', 637.48, 959);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (162, 'Vítor', 'None', 'Service', 'Moisturizing', 'Sá', 352.51, 8492);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (163, 'Emília', 'None', 'Product', 'Air Care', 'Soares', 192.34, 6815);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (164, 'Matias', 'None', 'Service', 'Detergent', 'Leite', 540.0, 4124);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (165, 'Dinis', 'None', 'Service', 'House Cleaners', 'Baptista', 36.61, 9586);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (166, 'Paulo', 'None', 'Product', 'Detergent', 'Rodrigues', 414.25, 7608);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (167, 'Diego', 'None', 'Product', 'Moisturizing', 'Martins', 867.0, 6552);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (168, 'Vitória', 'None', 'Service', 'Detergent', 'Vaz', 638.36, 8647);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (169, 'Bruno', 'None', 'Product', 'House Cleaners', 'Neto', 612.71, 5261);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (170, 'Santiago', 'None', 'Service', 'Desinfectant', 'Teixeira', 82.99, 5492);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (171, 'Benedita', 'None', 'Product', 'Desinfectant', 'Guerreiro', 42.37, 9789);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (172, 'Isabela', 'None', 'Service', 'Detergent', 'Freitas', 536.12, 6101);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (173, 'Carolina', 'None', 'Product', 'Air Care', 'Gonçalves', 535.38, 6264);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (174, 'Irina', 'None', 'Service', 'Detergent', 'Lopes', 213.63, 4226);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (175, 'Yara', 'None', 'Service', 'Detergent', 'Monteiro', 891.14, 778);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (176, 'Patrícia', 'None', 'Service', 'Detergent', 'Correia', 837.47, 3286);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (177, 'Rafaela', 'None', 'Product', 'Fabric Softener', 'Leite', 843.63, 1080);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (178, 'Vitória', 'None', 'Product', 'Detergent', 'Leite', 447.62, 1428);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (179, 'Simão', 'None', 'Service', 'House Cleaners', 'Loureiro', 300.4, 6515);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (180, 'Gonçalo', 'None', 'Service', 'Moisturizing', 'Valente', 693.89, 4359);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (181, 'João', 'None', 'Service', 'House Cleaners', 'Magalhães', 179.93, 5800);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (182, 'Miguel', 'None', 'Service', 'Fabric Softener', 'Cruz', 400.13, 5851);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (183, 'Pedro', 'None', 'Product', 'Desinfectant', 'Pinho', 355.73, 5282);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (184, 'Rita', 'None', 'Product', 'House Cleaners', 'Fonseca', 567.39, 1182);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (185, 'Gustavo', 'None', 'Service', 'Fabric Softener', 'Mendes', 402.53, 3158);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (186, 'José', 'None', 'Product', 'Moisturizing', 'Barros', 226.64, 3550);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (187, 'Kevin', 'None', 'Service', 'Air Care', 'Leal', 40.51, 5240);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (188, 'Luna', 'None', 'Service', 'Air Care', 'Cunha', 623.27, 7893);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (189, 'Dinis', 'None', 'Product', 'Air Care', 'Cruz', 943.43, 8374);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (190, 'Daniel', 'None', 'Product', 'Air Care', 'Freitas', 605.52, 2395);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (191, 'Maria', 'None', 'Product', 'Detergent', 'Jesus', 436.61, 3845);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (192, 'Sérgio', 'None', 'Service', 'Desinfectant', 'Faria', 52.71, 9390);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (193, 'Diego', 'None', 'Product', 'House Cleaners', 'Leal', 544.61, 3508);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (194, 'Joel', 'None', 'Product', 'Desinfectant', 'Sousa', 551.74, 4352);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (195, 'Joaquim', 'None', 'Service', 'House Cleaners', 'Antunes', 256.88, 9995);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (196, 'Álvaro', 'None', 'Product', 'Detergent', 'Soares', 306.97, 7985);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (197, 'Salomé', 'None', 'Product', 'Detergent', 'Simões', 476.69, 1079);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (198, 'Kévim', 'None', 'Service', 'Air Care', 'Guerreiro', 466.8, 5837);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (199, 'Vasco', 'None', 'Product', 'House Cleaners', 'Tavares', 762.52, 8434);
INSERT INTO `products` (`id`,`name`,`description`,`type`,`segment`,`brand`,`price`,`stock`) VALUES (200, 'Rafaela', 'None', 'Product', 'Air Care', 'Azevedo', 561.89, 3647);
